# Generated by Django 5.2.4 on 2025-11-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cartitem_is_offer_cartitem_offer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='offer_image',
        ),
    ]
