# Generated by Django 5.2.4 on 2025-11-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('products', '0002_initial_categories'),
    ]

    operations = [
    ]
