# Generated by Django 5.2.4 on 2025-11-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_offer_offerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='link_url',
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.DeleteModel(
            name='OfferImage',
        ),
    ]
