# Generated by Django 4.2.7 on 2026-01-28 06:22

from django.db import migrations


def copy_features_to_specs(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for p in Product.objects.all():
        # some DB backends may already have dropped the column; guard safely
        feats = getattr(p, 'features', None)
        if not feats:
            continue
        specs = p.specifications or {}
        existing = specs.get('Características', [])
        if not isinstance(existing, list):
            existing = [existing]
        for f in feats:
            if f not in existing:
                existing.append(f)
        specs['Características'] = existing
        p.specifications = specs
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offer_price'),
    ]

    operations = [
        migrations.RunPython(copy_features_to_specs, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
