# Generated by Django 4.2.7 on 2025-12-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profession',
        ),
    ]
