<<<<<<< HEAD
# Generated by Django 4.2.7 on 2026-01-29 03:00
=======
# Generated by Django 4.2.7 on 2025-12-11 08:04
>>>>>>> origin/rama_maikel

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
